config/routes.rb
Www::Application.routes.draw do
  
  resources :auth_sources
  resources :auth_sources_ldap

  match '/' => 'projects#dashboard', :as => :home
  match ':controller/service.wsdl' => '#wsdl'

  resources :hosts
  resources :recipes do
    collection do
      get :preview
    end
  end

  resources :projects do
    member do
      get :dashboard
    end

    resources :project_configurations
    resources :stages do
      match :recipes, :on => :member
      member do
        get :capfile
        get :tasks
      end

      resources :stage_configurations
      resources :roles
      resources :deployments do
        collection do
          get :latest
        end

        member do
          post :cancel
        end
      end
    end
  end

  resources :users do

    member do
      get :deployments
      post :enable
    end
  end

  resources :sessions do
    collection do
      get :version
    end
  end
  


  match '/signup' => 'users#new', :as => :signup
  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/stylesheets/application.css' => 'stylesheets#application', :as => :stylesheet
  match '/:controller(/:action(/:id))'
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_and_belongs_to_many :stages
  
  validates_uniqueness_of :name
  validates_presence_of :name, :body
  validates_length_of :name, :maximum => 250

  attr_accessible :name, :body, :description
  
  scope :ordered, :order => "name ASC"
  
  version_fu rescue nil # hack to silence migration errors when the original table is not there

  validate :check_syntax

  def check_syntax
   return if self.body.blank?

   result = ""
   Open4::popen4 "ruby -wc" do |pid, stdin, stdout, stderr|
     stdin.write body
     stdin.close
     output = stdout.read
     errors = stderr.read
     result = output.empty? ? errors : output
   end
   
   unless result == "Syntax OK"
     line = $1.to_i if result =~ /^-:(\d+):/
     errors.add(:body, "syntax error at line: #{line}") unless line.nil?
   end
  rescue => e
    Rails.logger.error "Error while validating recipe syntax of recipe #{self.id}: #{e.inspect} - #{e.backtrace.join("\n")}"
  end
 
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :ensure_can_manage_recipes, :except => [:show, :index]
  
  # GET /recipes
  # GET /recipes.xml
  def index
    @recipes = Recipe.find(:all)

    respond_to do |format|
      format.html # index.rhtml
      format.xml  { render :xml => @recipes.to_xml }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.xml
  def show
    find_recipe_with_version
    
    respond_to do |format|
      format.html # show.rhtml
      format.xml  { render :xml => @recipe.to_xml }
    end
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1;edit
  def edit
    find_recipe_with_version
  end

  # POST /recipes
  # POST /recipes.xml
  def create
    @recipe = Recipe.new((params[:recipe] || {}).merge(:user_id => current_user.id))

    respond_to do |format|
      if @recipe.save
        flash[:notice] = 'Recipe was successfully created.'
        format.html { redirect_to recipe_url(@recipe) }
        format.xml  { head :created, :location => recipe_url(@recipe) }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @recipe.errors.to_xml }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.xml
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes((params[:recipe] || {}).merge(:user_id => current_user.id))
        flash[:notice] = 'Recipe was successfully updated.'
        format.html { redirect_to recipe_url(@recipe) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @recipe.errors.to_xml }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.xml
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:notice] = 'Recipe was successfully deleted.'
    
    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.xml  { head :ok }
    end
  end
  
  def preview
    @recipe = Recipe.new(params[:recipe])

    render "recipes/_preview", :locals => {:recipe => @recipe}, :layout => false
  end
  
  private
  def find_recipe_with_version
    @recipe = Recipe.find(params[:id])
    
    unless params[:version].blank?
      recipe_version = @recipe.find_version(params[:version])
      @recipe.attributes = @recipe.find_version(params[:version]).attributes if recipe_version
    end
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def highlight_syntax(code)
    Syntax::Convertors::HTML.for_syntax("ruby").convert(code)
  end
  
  def all_recipe_versions
    versions = @recipe.versions.collect{|v| ["Version #{v.version}", v.version.to_s]}.reverse
    versions[0] = ["Latest version", ""]
    versions
  end
  
  def not_latest_version
    !params[:version].blank? && params[:version].to_i < @recipe.versions.latest.version
  end
end

app/views/recipes/_form.html.erb
<% flashed_errors(:recipe) %>
<p>
  <b>Name</b><br />
  <%= text_field 'recipe', 'name', :style =>'width:300px; ' %>
</p>

<p>
  <b>Description</b><br />
  <%= text_area 'recipe', 'description', :style =>'width:663px; height: 100px;' %>
</p>

<p>
  <b>Body</b><br />
  <%= text_area 'recipe', 'body', :style =>'width:663px; height: 400px;' %>
</p>

<%= observe_field "recipe_body", :frequency => 2.5, :with => "Form.Element.serialize('recipe_body')", :url => preview_recipes_url, :update => "preview" %>
<div id="preview_fieldset">
  <fieldset class="fieldset" style="width:560px;">
    <legend>Code-Preview</legend>
    <div id="preview">
      <%= render(:partial => 'preview', :locals => {:recipe => @recipe}) %>
    </div>
  </fieldset>
<br/>
</div>

app/views/recipes/_preview.html.erb
  <div class="log_output ruby">
    <%= raw highlight_syntax(recipe.body || '') %>
  </div>

app/views/recipes/_stages.html.erb
<% if @recipe.stages.empty? %>
<br/>
    No stages are using this recipe.
<br/>
<% else %>
  <table class="sortable">
    <tr>
      <th width="50%">Project</th>
      <th width="50%">Stage</th>
    </tr>
  <% for stage in @recipe.stages %>
    <tr class="<%= cycle :even, :odd, :name => 'stages' %>">
      <td><%= link_to stage.project.name, project_path(stage.project) %></td>
      <td><%= link_to stage.name, project_stage_path(stage.project, stage) %></td>
    </tr>
  <% end %>
  </table>
<% end %>

app/views/recipes/edit.html.erb
<%= form_for(:recipe, :url => recipe_path(@recipe), :html => { :method => :put }) do |f| %>

  <%= render(:partial => 'form')%>

  <%= link_to 'Back to recipe', recipe_path(@recipe), :class => 'arrow_link ontheright'%>

  <p>
    <%= submit_tag "Update" %>
  </p>
<% end %>


<% content_for(:breadcrumb) do %>
    <%= link_to "Back to recipe", recipe_path(@recipe), :style => "float:right", :class => "arrow_link" %>
    <%= link_to "Recipes", recipes_path %> &gt; 
    Recipe <%= link_to @recipe.name, recipe_path(@recipe) %>  &gt; 
    Edit
<% end %>

<% content_for(:page_title) do %>
  <% @page_title = "Edit recipe #{h(@recipe.name)}" %>
  <h2>Edit recipe <%= link_to @recipe.name, recipe_path(@recipe) %></h2>
<% end %>

app/views/recipes/index.html.erb
<fieldset class="fieldset">
  <legend> <%= pluralize(Recipe.count, 'Recipe')%> listed</legend>

<% if @recipes.empty? %>
  <br/>
    No recipes configured yet.<br />
    Recipes are custom Capistrano tasks and variables that can be used across stages.
  <br/>
<% else %>
  <table class="sortable">
    <tr>
      <th width="39%">Name</th>
      <th width="59%">Description</th>
      <th width="1%">#Stages</th>
      <th width="1%">Created At</th>
    </tr>
    <% for recipe in @recipes %>
      <tr class="<%= cycle :even, :odd, :name => 'recipes'  %>">
        <td><%= link_to recipe.name, recipe_path(recipe) %></td>
        <td><%= recipe.description %></td>
        <td><%= recipe.stages.count %></td>
        <td><%= recipe.created_at.to_s(:date_with_day) rescue nil %></td>
        <% if current_user.can_manage_recipes? %>
          <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
          <td><%= link_to 'Delete', recipe_path(recipe), :confirm => 'Are you sure?', :method => :delete %></td>
        <% end %>
      </tr>
    <% end %>
  </table>
<% end %>

<% if current_user.can_manage_recipes? %>
  <br />
  <%= link_to 'New recipe', new_recipe_path, :class => 'arrow_link' %>
<% end %>

</fieldset>

<% content_for(:breadcrumb) do %>
    <%= link_to "Recipes", recipes_path %>
<% end %>

<% content_for(:page_title) do %>
  <% @page_title = "Recipes" %>
  <h2>Recipes</h2>
<% end %>

app/views/recipes/new.html.erb
<%= form_for(:recipe, :url => recipes_path) do |f| %>

  <%= render(:partial => 'form')%>

  <%= link_to 'Back to recipes', recipes_path, :class => 'arrow_link ontheright' %>

  <p>
    <%= submit_tag "Create recipe" %>
  </p>
<% end %>



<% content_for(:breadcrumb) do %>
    <%- if current_user.can_manage_recipes? -%>
      <%= link_to "Manage recipes", recipes_path, :style => "float:right", :class => "arrow_link" %>
    <%- end -%>
    <%= link_to "Recipes", recipes_path %> &gt; 
    New
<% end %>

<% content_for(:page_title) do %>
  <% @page_title = "New recipe" %>
  <h2>New recipe</h2>
<% end %>

app/views/recipes/show.html.erb
<div class="special_box">
  <div class="special_box_top"></div>
  <div class="special_box_middle recipe_box"></div>
  <div class="special_box_bottom"></div>
</div>

<div class="box">
  <div class="box_top"></div>
  <div class="box_middle">
		<p>
		  <b>#Stages:</b>
		  <%= @recipe.stages.count %>
		</p>
		<p>
		  <b>#Versions:</b>
		  <%= @recipe.version %>
		</p>
    <br/>
    <p>
		  <%= select_tag "version", options_for_select(all_recipe_versions, params[:version]), :id => "recipe_version" %>
		  <%= link_to_function "Show", "location.href='#{recipe_path(@recipe)}?version=' + $F('recipe_version')", :class => "arrow_link" %>
		  <%= link_to "Rollback", edit_recipe_path(@recipe, :version => params[:version]), :class => "arrow_link" if not_latest_version and current_user.admin? %>
    </p>
		<% if current_user.can_manage_recipes? %>
	  	<%= link_to 'Edit latest version', edit_recipe_path(@recipe), :class => 'arrow_link' %> |
	  	<%= link_to 'Delete all versions', recipe_path(@recipe), :confirm => 'Are you sure?', :method => :delete, :class => 'arrow_link' %>
	  <% end %>
  </div>
  <div class="box_bottom"></div>
</div>

<div class="clear"></div>
<br />

<fieldset class="fieldset" style="width: 212px; margin-left: 28px; float: right;">
  <legend>Description</legend>
  <p>
    <%=web_friendly_text @recipe.description %>
 	</p>
  <%= link_to 'Edit', edit_recipe_path(@recipe), :class => 'arrow_link' %>
</fieldset>

<fieldset class="fieldset">
  <legend>Used by stage</legend>
  <%= render(:partial => 'stages')%>
</fieldset>

<div class="clear"></div>

<div class="clear"></div>
<br />

<fieldset class="fieldset">
  <legend>Body</legend>
  <%= render :partial => 'preview', :locals => {:recipe => @recipe} %>
</fieldset>

<% content_for(:breadcrumb) do %>
    <%- if current_user.can_manage_recipes? -%>
      <%= link_to "Manage recipes", recipes_path, :style => "float:right", :class => "arrow_link" %>
    <%- end -%>
    <%= link_to "Recipes", recipes_path %> &gt; 
    Recipe <%= link_to @recipe.name, recipe_path(@recipe) %> 
<% end %>

<% content_for(:page_title) do %>
  <% @page_title = "Recipe #{h(@recipe.name)}" %>
  <h2>Recipe <%= link_to @recipe.name, recipe_path(@recipe) %></h2>
<% end %>