config/routes.rb
Www::Application.routes.draw do
  
  resources :auth_sources
  resources :auth_sources_ldap

  match '/' => 'projects#dashboard', :as => :home
  match ':controller/service.wsdl' => '#wsdl'

  resources :hosts
  resources :recipes do
    collection do
      get :preview
    end
  end

  resources :projects do
    member do
      get :dashboard
    end

    resources :project_configurations
    resources :stages do
      match :recipes, :on => :member
      member do
        get :capfile
        get :tasks
      end

      resources :stage_configurations
      resources :roles
      resources :deployments do
        collection do
          get :latest
        end

        member do
          post :cancel
        end
      end
    end
  end

  resources :users do

    member do
      get :deployments
      post :enable
    end
  end

  resources :sessions do
    collection do
      get :version
    end
  end
  


  match '/signup' => 'users#new', :as => :signup
  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/stylesheets/application.css' => 'stylesheets#application', :as => :stylesheet
  match '/:controller(/:action(/:id))'
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :stages, :dependent => :destroy, :order => 'name ASC'
  has_many :deployments, :through => :stages
  has_many :configuration_parameters, :dependent => :destroy, :class_name => "ProjectConfiguration", :order => 'name ASC'

  has_many :user_project_links, :dependent => :destroy
  has_many :users, :through => :user_project_links
    
  validates_uniqueness_of :name
  validates_presence_of :name
  validates_length_of :name, :maximum => 250
  validates_inclusion_of :template, :in => ProjectConfiguration.templates.keys
  
  after_create :create_template_defaults
  
  attr_accessible :name, :description, :template, :archived
  
  named_scope :active,
    :include    => [:users, {:stages => [:hosts, :recipes]}, :configuration_parameters, :user_project_links],
    :conditions => {:archived => false},
    :order      => "projects.name ASC"
  
  # creates the default configuration parameters based on the template
  def create_template_defaults
    unless template.blank?
      ProjectConfiguration.templates[template]::CONFIG.each do |k, v|
        config = self.configuration_parameters.build(:name => k.to_s, :value => v.to_s)

        if k.to_sym == :application          
          config.value = self.name.gsub(/[^0-9a-zA-Z]/,"_").underscore
        end  
        config.save!
      end
    end
  end
  
  def editable_by?(_user)
    _user.admin? || _user.can_manage_projects? || (!self.archived? && _user.projects.include?(self))
  end
  
  def viewable_by?(_user)
    _user.admin? || _user.can_manage_projects? || (!self.archived? && _user.projects.include?(self))
  end
  
  # returns a string with all custom tasks to be loaded by the Capistrano config
  def tasks
    ProjectConfiguration.templates[template]::TASKS
  end
  
  # returns a better form of the project name for use inside Capistrano recipes
  def webistrano_project_name
    self.name.underscore.gsub(/[^a-zA-Z0-9\-\_]/, '_')
  end
  
  def recent_deployments(limit=3)
    self.deployments.find(:all, :limit => limit, :order => 'deployments.created_at DESC')
  end
  
  def prepare_cloning(other)
    self.name = "Clone of #{other.name}"
    self.description = "Clone of #{other.name}: #{other.description}"
    self.template = other.template
  end
  
  def clone(other)  
    self.stages.destroy_all
    self.configuration_parameters.destroy_all
      
    other.configuration_parameters.each do |conf|
      self.configuration_parameters << ProjectConfiguration.new(:name => conf.name, :value => conf.value, :prompt_on_deploy => conf.prompt_on_deploy)
    end
    
    other.stages.each do |stage|
      new_stage = Stage.new
      new_stage.project = self
      new_stage.name = stage.name
      new_stage.alert_emails = stage.alert_emails
      new_stage.save!
      
      stage.configuration_parameters.each do |conf|
        new_stage.configuration_parameters << StageConfiguration.new(:name => conf.name, :value => conf.value, :prompt_on_deploy => conf.prompt_on_deploy)
      end
      
      stage.recipes.each do |recipe|
        new_stage.recipes << recipe
      end

      stage.roles.each do |role|
        new_stage.roles << Role.new(role.attributes)
      end
    end
    
    self.reload
  end
    
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  before_filter :load_templates, :only => [:new, :create, :edit, :update]
  before_filter :load_project, :only => [:show, :destroy, :edit, :update]
  before_filter :ensure_can_access_project, :except => [:new, :create, :dashboard, :index]
  before_filter :ensure_can_edit_project, :only => [:edit, :update]
  before_filter :ensure_can_manage_projects, :only => [:new, :create, :destroy]
  
  # GET /projects/dashboard
  def dashboard
    @deployments = Deployment.find(:all,
                                   :include    => {:stage => :project},
                                   :conditions => {'stages.project_id' => @sidebar_projects},
                                   :order      => 'deployments.created_at DESC',
                                   :limit      => 3)

    respond_to do |format|
      format.html # dashboard.rhtml
    end
  end
  
  # GET /projects
  # GET /projects.xml
  def index
    @projects = Project.active.select { |p| 
      ensure_can_access_project(p)
    }
    
    respond_to do |format|
      format.html # index.rhtml
      format.xml  { render :xml => @projects.to_xml }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @can_edit_project = current_user.can_edit?(@project)

    respond_to do |format|
      format.html # show.rhtml
      format.xml  { render :xml => @project.to_xml }
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
    if load_clone_original
      @project.prepare_cloning(@original)
      render :action => 'clone' and return
    end
  end

  # GET /projects/1;edit
  def edit
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(params[:project])
    
    if load_clone_original
      action_to_render = 'clone'  
    else
      action_to_render = 'new'  
    end
    
    @project.user_ids = params[:project][:user_ids] || []
      
    respond_to do |format|
      if @project.save
        @project.clone(@original) if load_clone_original
        
        flash[:notice] = 'Project was successfully created.'
        format.html { redirect_to project_url(@project) }
        format.xml  { head :created, :location => project_url(@project) }
      else
        format.html { render :action => action_to_render }
        format.xml  { render :xml => @project.errors.to_xml }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project.user_ids = params[:project][:user_ids] || []

    respond_to do |format|
      if @project.update_attributes(params[:project])
        flash[:notice] = 'Project was successfully updated.'
        format.html { redirect_to(@project.archived? ? projects_path : project_url(@project))}
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors.to_xml }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project.destroy

    respond_to do |format|
      flash[:notice] = 'Project was successfully deleted.'
      format.html { redirect_to projects_url }
      format.xml  { head :ok }
    end
  end
  
  protected
  def load_templates
    @templates = ProjectConfiguration.templates.sort.collect do |k,v|
      [k.to_s.titleize, k.to_s]
    end  
    
    @template_infos = ProjectConfiguration.templates.collect do |k,v|
      [k.to_s, v::DESC]
    end
  end
  
  def load_clone_original
    if params[:clone]
      @original = Project.active.find(params[:clone])
    else
      false
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  
  def clone_form_path(project)
    "#{new_project_path}?clone=#{project.id}"
  end
  
  def clone_path(project)
    "#{projects_path}?clone=#{project.id}"
  end
  
end

app/views/projects/_configs.html.erb
<% if @project.configuration_parameters.empty? %>
  <br/>
    <strong>No project wide configuration added yet.</strong><br/>
     Project configuration is overridden by stage configurations. 
  </p>
<% else %>
  <table class="sortable">
    <tr>
      <th width="1%">Name</th>
      <th width="98%">Value</th>
      <th width="1%">Prompt?</th>
    </tr>
  <% for config in @project.configuration_parameters %>
    <tr class="<%= cycle :even, :odd, :name => 'configs' %>">
      <td title="<%= config.name %>"><%= truncate(h(config.name), :length => 25) %></td>
      <td title="<%= config.value %>"><%= truncate(hide_password_in_value(config), :length => 45) %></td>
      <td><%= config.prompt_status_in_html %></td>
      <%- if current_user.can_edit?(@project) -%>
        <td><%= link_to 'Edit', edit_project_project_configuration_path(@project, config) %></td>
        <td><%= link_to 'Delete', project_project_configuration_path(@project, config), :confirm => 'Are you sure?', :method => :delete %></td>
      <%- end -%>
    </tr>
  <% end %>
  </table>
<% end %>

app/views/projects/_deployments.html.erb
<% if @project.deployments.empty? %>
  <br/>
    This project was never deployed. 
  <br/>
<% else %>
<% @project.recent_deployments.each do |deployment| %>
    <%= render(:partial => 'deployments/list_item', :locals => {:deployment => deployment}) %>
  <% end %>
<% end %>
<br />

app/views/projects/_form.html.erb
<% flashed_errors(:project) %>
<p>
  <b>Name</b><br />
  <%= text_field 'project', 'name', :style =>'width:330px;' %>
</p>
<p>
  <b>Project Type</b><br />
  <%= select('project', 'template', @templates, { :include_blank => false }) %>
</p>
<p>
  <b>Description</b><br />
  <%= text_area 'project', 'description', :style =>'width:330px; height: 100px' %>
</p>

<p>
  <%= check_box 'project', 'archived', :class => 'noframe' %> <b>Archived?</b>
</p>

<h3>User access</h3>
<%- User.all.each do |user| -%>
  <p>
    <%= check_box_tag "project[user_ids][]", user.id, @project.users.include?(user), :class => 'noframe' %> <b><%= user.login %></b> 
  </p>
<%- end -%>



<% content_for(:page_scripts) do %>
 <script type="text/javascript">
 
    Event.observe(window, 'load', function(){
      Event.observe('project_template', 'change', show_template_info);
      
      // show info for already chosen template
      show_template_info();
    });
 
   function show_template_info(){
     hide_all_infos();
     var info_to_show = $F('project_template') + '_desc';
     $(info_to_show).show();
   }
   
   function hide_all_infos(){
     <% for template in @template_infos %>
       $('<%= template.first %>_desc').hide();
     <% end %>
   }

 </script>
<% end %>
<% content_for(:action_box) do %>
<div class="small_box">
  <div class="small_box_top"></div>
  <div class="small_box_middle" style="min-height: 230px; *height: 230px;">
		 <h3>Project Type:</h3>
		   <% for template in @template_infos %>
		     <div id="<%= template.first %>_desc" style="display:none;">
		         <b><%= template.first.to_s.titleize %>:</b><br />
		         <%= template.last %>
		     </div>
		   <% end %>
  </div>
  <div class="small_box_bottom"></div>
</div>
<% end %>

app/views/projects/_stages.html.erb
<% if @project.stages.empty? %>
<br/>
    <strong>No stages configured yet.</strong><br/> Stages represent one deployment scenario of a project. Typical stages are a 'Prod', 'Test' and 'Dev' stage.
<br/>
<% else %>
  <table class="sortable">
    <tr>
      <th width="34%">Name</th>
      <th width="33%">#Hosts</th>
      <th width="33%">#Deployments</th>
    </tr>
  <% for stage in @project.stages %>
    <tr class="<%= cycle :even, :odd, :name => 'stages' %>">
      <td><%= link_to stage.name, project_stage_path(@project, stage) %></td>
      <td><%= stage.hosts.count  %></td>
      <td><%= stage.deployments.count  %></td>
      <td><%= link_to 'Edit', edit_project_stage_path(@project, stage) %></td>
      <td><%= link_to 'Delete', project_stage_path(@project, stage), :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
  </table>
<% end %>

app/views/projects/_welcome.html.erb
<fieldset class="fieldset">
  <legend>Introduction and help</legend>
  <div style="float: right; padding: 10px 5px 5px 5px;">
    <a href="https://github.com/peritor/webistrano" target="_blank"><%= image_tag('peritor_theme/webistrano_screenshot.png', :border => '0', :width => '200', :height => '151')%></a>
  </div>
  <div style="padding-top: 5px;">
   Welcome to Webistrano. Your first steps should be to create a project with a stage.
   This stage can then be deployed once you made at least one host known to Webistrano.
   <br /><br />
   For help and more documentation, see
   <br />
   <ul>
     <li><a href="https://github.com/peritor/webistrano/wiki">Wiki</a></li>
     <li><a href="https://github.com/peritor/webistrano/wiki/Configuration-Parameters">Configuration Parameters</a></li>
     <li><a href="https://github.com/peritor/webistrano/wiki/FAQ---Frequently-Asked-Questions">FAQ</a></li>
   </ul>
   <br />
   Webistrano is Open Source. Paid support is available by <a href="http://www.peritor.com">Peritor Consulting</a>.
  </div>
</fieldset>

<br />

app/views/projects/clone.html.erb
<%= form_for(:project, :url => clone_path(@original)) do |f| %>

  <%= render(:partial => 'form')%>
  
  <%= link_to 'Back to projects', projects_path, :class => 'arrow_link ontheright', :style => 'margin-right: 80px' %>

  <p>
    <%= submit_tag "Clone" %>
  </p>
<% end %>

<% content_for(:breadcrumb) do %>
    <%= link_to "Back to project", project_path(@original), :style => "float:right", :class => "arrow_link" %>
    <%= link_to "Projects", projects_path %> &gt; 
    Clone <%= link_to @original.name, project_path(@original) %> 
<% end %>

<% content_for(:page_title) do %>
  <% @page_title = "Clone project #{h(@original.name)}" %>
  <h2>Clone project</h2>
<% end %>

app/views/projects/dashboard.html.erb
<%= render :partial => 'projects/welcome' %>

<fieldset class="fieldset">
  <legend>Recent deployments</legend>
  <% if @deployments.empty? %>
    <br/>
      No recent deployments.
    <br/>
  <% else %>
    <% @deployments.each do |deployment| %>
      <%= render(:partial => 'deployments/list_item', :locals => {:deployment => deployment}) %>
    <% end %>
  <% end %>
</fieldset>

<br />

<% content_for(:page_title) do %>
  <% @page_title = "Welcome to Webistrano" %>
  <h2>Welcome to Webistrano</h2>
<% end %>

app/views/projects/edit.html.erb
<%= form_for(:project, :url => project_path(@project), :html => { :method => :put }) do |f| %>
  
  <%= render(:partial => 'form')%>

  <%= link_to 'Back to project', project_path(@project), :class => 'arrow_link ontheright', :style => 'margin-right: 80px' %>

  <p>
    <%= submit_tag "Update project" %>
  </p>

<% end %>

<% content_for(:breadcrumb) do %>
    <%= link_to "Back to project", project_path(current_project), :style => "float:right", :class => "arrow_link" %>
    <%= link_to "Projects", projects_path %> &gt; 
    Project <%= link_to current_project.name, project_path(current_project) %> &gt; 
    Edit
<% end %>

<% content_for(:page_title) do %>
  <% @page_title = "Edit project #{h(current_project.name)}" %>
  <h2>Edit <%= link_to current_project.name, project_path(current_project) %></h2>
<% end %>

app/views/projects/index.html.erb
<fieldset class="fieldset">
  <legend> <%= pluralize(Project.count, 'Project')%> listed</legend>

<% if @projects.empty? %>
<br/>
    No projects configured yet.<br />
    Please add a project.
  <br/>
<% else %>
  <table class="sortable">
    <tr>
      <th width="1%">Name</th>
      <th width="96%">Description</th>
      <th width="1%">#Stages</th>
      <th width="1%">#Deploy.</th>
      <th width="1%">Created At</th>
    </tr>
    <% for project in @projects %>
      <tr class="<%= cycle :even, :odd, :name => 'projects'  %>">
        <td><%= link_to project.name, project_path(project) %></td>
        <td><%= project.description %></td>
        <td><%= project.stages.count %></td>
        <td><%= project.deployments.count %></td>
        <td><%= project.created_at.to_s(:date_with_day) %></td>
        <%- if current_user.can_edit?(project) -%>
          <td><%= link_to 'Edit', edit_project_path(project) %></td>
          <td><%= link_to 'Clone', clone_form_path(project) %></td>
          <td><%= link_to 'Delete', project_path(project), :confirm => 'Are you sure?', :method => :delete %></td>
        <%- end -%>
      </tr>
    <% end %>
  </table>
<% end %>

<br />

<%- if current_user.admin? || current_user.manage_projects? -%>
  <%= link_to 'New project', new_project_path, :class => 'arrow_link' %>
<%- end -%>

</fieldset>

<% content_for(:breadcrumb) do %>
	<%= link_to "Projects", projects_path %>
<% end %>

<% content_for(:page_title) do %>
  <% @page_title = "Projects" %>
  <h2>Projects</h2>
<% end %>

app/views/projects/new.html.erb
<%= form_for(:project, :url => projects_path) do |f| %>
<div style="width:335px;">

  <%= render(:partial => 'form')%>
  
  <%= link_to 'Back to projects', projects_path, :class => 'arrow_link ontheright' %>

  <p>
    <%= submit_tag "Create" %>
  </p>
</div>
<% end %>


<% content_for(:breadcrumb) do %>
    <%- if current_user.can_manage_projects? -%>
      <%= link_to "Manage Projects", projects_path, :style => "float:right", :class => "arrow_link" %>
    <%- end -%>
    <%= link_to "Projects", projects_path %> &gt; 
    New
<% end %>

<% content_for(:page_title) do %>
  <% @page_title = "New project" %>
  <h2>New project</h2>
<% end %>

app/views/projects/show.html.erb
<div class="special_box">
  <div class="special_box_top"></div>
  <div class="special_box_middle stages_box">
    <% if @project.stages.count > 0 %>
      <p><strong>Choose a stage:</strong></p>
      <% for stage in @project.stages %>
          <p><%= link_to stage.name, project_stage_path(@project, stage, :class => 'arrow_link')  %></p>
      <% end %>
    <% else %>  
      <p><strong>No stage configured yet</strong></p>
      <%- if current_user.can_edit?(@project) -%>
        <%= link_to 'New stage', new_project_stage_path(@project), :class => 'arrow_link' %>
      <%- end -%>
    <% end %>
  </div>
  <div class="special_box_bottom"></div>
</div>

<div class="box">
  <div class="box_top"></div>
  <div class="box_middle">
		<p>
		<b>Description:</b>
		  <%= @project.description %>
		</p>
		<p>
		  <b>Project Type:</b>
		  <%= @project.template %>
		</p>
		<p>
    <b>#Deployments:</b>
	  <%= @project.deployments.count %>
 		</p><br />
 		<%- if current_user.can_edit?(@project) -%>
  	  <%= link_to 'Edit project', edit_project_path(@project), :class => 'arrow_link' %> | 
	    <%= link_to 'Clone project', clone_form_path(@project), :class => 'arrow_link' %> | 
 		  <%= link_to 'Delete project', project_path(@project), :confirm => 'Are you sure?', :method => :delete, :class => 'arrow_link' %>
 		<%- end -%>
  </div>
  <div class="box_bottom"></div>
</div>

<div class="clear"></div>
<br>

<fieldset class="fieldset">
  <legend>Project configuration</legend>
  <%= render(:partial => 'configs')%>
  <br />
  <%- if current_user.can_edit?(@project) -%>
    <%= link_to 'New configuration', new_project_project_configuration_path(@project), :class => 'arrow_link' %>
  <%- end -%>
</fieldset>

<br /><br />

<fieldset class="fieldset">
  <legend>Stages</legend>
  <%= render(:partial => 'stages')%>
  <br />
  <%- if current_user.can_edit?(@project) -%>
    <%= link_to 'New stage', new_project_stage_path(@project), :class => 'arrow_link' %>
  <%- end -%>
</fieldset>

<br /><br />

<fieldset class="fieldset">
  <legend>Recent Deployments</legend>
  <%= render(:partial => 'deployments')%>
  <br />
</fieldset>

<br /><br />

<fieldset class="fieldset">
  <legend>Users</legend>
  <%- @project.users.each do |u| -%>
    <%= u.login %><br />
  <%- end -%>
</fieldset>

<% content_for(:breadcrumb) do %>
    <%- if current_user.can_manage_projects? -%>
      <%= link_to "Manage projects", projects_path, :style => "float:right", :class => "arrow_link" %>
    <%- end -%>
    <%= link_to "Projects", projects_path %> &gt; 
    Project <%= link_to current_project.name, project_path(current_project) %> 
<% end %>

<% content_for(:page_title) do %>
  <% @page_title = "Project #{h(current_project.name)}" %>
  <h2>Project <%= link_to current_project.name, project_path(current_project) %></h2>
<% end %>