config/routes.rb
Www::Application.routes.draw do
  
  resources :auth_sources
  resources :auth_sources_ldap

  match '/' => 'projects#dashboard', :as => :home
  match ':controller/service.wsdl' => '#wsdl'

  resources :hosts
  resources :recipes do
    collection do
      get :preview
    end
  end

  resources :projects do
    member do
      get :dashboard
    end

    resources :project_configurations
    resources :stages do
      match :recipes, :on => :member
      member do
        get :capfile
        get :tasks
      end

      resources :stage_configurations
      resources :roles
      resources :deployments do
        collection do
          get :latest
        end

        member do
          post :cancel
        end
      end
    end
  end

  resources :users do

    member do
      get :deployments
      post :enable
    end
  end

  resources :sessions do
    collection do
      get :version
    end
  end
  


  match '/signup' => 'users#new', :as => :signup
  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/stylesheets/application.css' => 'stylesheets#application', :as => :stylesheet
  match '/:controller(/:action(/:id))'
end

app/models/stage.rb
class Stage < ActiveRecord::Base  
  belongs_to :project
  has_and_belongs_to_many :recipes
  has_many :roles, :dependent => :destroy, :order => "name ASC"
  has_many :hosts, :through => :roles, :uniq => true
  has_many :configuration_parameters, :dependent => :destroy, :class_name => "StageConfiguration", :order => "name ASC"
  has_many :deployments, :dependent => :destroy, :order => "created_at DESC"
  belongs_to :locking_deployment, :class_name => 'Deployment', :foreign_key => :locked_by_deployment_id 
  
  validates_uniqueness_of :name, :scope => :project_id
  validates_length_of :name, :maximum => 250
  validates_presence_of :project, :name
  validates_inclusion_of :locked, :in => [0,1]

  validate :do_validate

  attr_accessible :name, :alert_emails

  # fake attr (Hash) that hold info why deployment is not possible
  # (think model.errors lite)
  attr_accessor :deployment_problems
  
  EMAIL_BASE_REGEX = '([^@\s\,\<\>\?\&\;\:]+)@((?:[\-a-z0-9]+\.)+[a-z]{2,})'
  EMAIL_REGEX = /^#{EMAIL_BASE_REGEX}$/i
    
  def do_validate
    unless self.alert_emails.blank?
      self.alert_emails.split(" ").each do |email|
        unless email.match(EMAIL_REGEX)
          self.errors.add('alert_emails', 'format is not valid, please seperate email addresses by space') 
          break
        end
      end
    end
  end
  
  # wrapper around alert_emails, returns an array of email addresses
  def emails
    if self.alert_emails.blank?
      []
    else
      self.alert_emails.split(" ")
    end
  end
  
  # returns an array of ConfigurationParameters that is a result of the projects configuration overridden by the stage config 
  def effective_configuration(key=nil) 
    project_configs = self.project.configuration_parameters.dup
    my_configs = self.configuration_parameters.dup
    
    cleaned_project_configs = project_configs.delete_if{|x| my_configs.collect(&:name).collect(&:to_s).include?(x.name.to_s) }
    
    effec_conf = cleaned_project_configs + my_configs
    effec_conf.sort!{|x, y| x.name <=> y.name }

    if key.blank?
      return effec_conf
    else # specific key look up
      effec_conf.delete_if{|x| x.name.to_s != key.to_s}.first
    end
  end
  
  # returns @deployment_problems, but before sets it through `deployment_possible?`
  def deployment_problems
    @deployment_problems = @deployment_problems || {}
    
    deployment_possible?
    
    @deployment_problems
  end
  
  # tells wether a deployment is possible/allowed
  # by checking that all needed roles are present and some
  # essential variables are set
  def deployment_possible?
    # check roles and vars
    needed_roles_present?
    needed_vars_set?
    
    # when there are not deployment_problems, deployment is possible
    @deployment_problems.blank?
  end
  
  def editable_by?(_user)
    self.project.editable_by?(_user)
  end
  
  def viewable_by?(_user)
    self.project.viewable_by?(_user)
  end
  
  def needed_roles_present?
    # for now just check if there are any roles
    if self.roles.empty? 
      self.add_deployment_problem(:roles, 'no hosts are present. You need at least one host.')
    end
  end
  
  def needed_vars_set?
    needed_vars = [:repository, :application]
    needed_vars.each do |key|
      if self.effective_configuration(key).blank?
        self.add_deployment_problem(key, "the configuration parameter '#{key.to_s}' needs to be set.")
      end
    end
  end
  
  # returns an array of all effective configurations that need a prompt
  def prompt_configurations
    res = effective_configuration.delete_if do |config|
      !config.prompt?
    end
  end
  
  # returns an array of all effective configurations that do not need a prompt
  def non_prompt_configurations
    res = effective_configuration.delete_if do |config|
      config.prompt?
    end
  end
  
  def recent_deployments(limit=3)
    self.deployments.find(:all, :limit => limit, :order => 'deployments.created_at DESC')
  end
  
  # returns a better form of the stage name for use inside Capistrano recipes
  def webistrano_stage_name
    self.name.underscore.gsub(/[^a-zA-Z0-9\-\_]/, '_')
  end
  
  # returns a lists of all availabe tasks for this stage
  def list_tasks
    d = Deployment.new
    d.stage = self
    deployer = Webistrano::Deployer.new(d)
    begin
      deployer.list_tasks.collect { |t| {:name => t.fully_qualified_name, :description => t.description} }.delete_if{|t| t[:name] == 'shell' || t[:name] == 'invoke'}
    rescue Exception => e
      Rails.logger.error("Problem listing tasks of stage #{id}: #{e} - #{e.backtrace.join("\n")} ")
      [{:name => "Error", :description => "Could not load tasks - syntax error in recipe definition?"}]
    end
  end
    
  def lock
    other_self = self.class.find(self.id, :lock => true)
    other_self.update_attribute(:locked, 1)
    self.reload
  end
  
  def unlock
    other_self = self.class.find(self.id, :lock => true)
    other_self.update_attribute(:locked, 0)
    other_self.update_attribute(:locked_by_deployment_id, nil)
    self.reload
  end
  
  def lock_with(deployment)
    raise ArgumentError, "stage #{self.id.inspect} must be locked before attaching lock_info to it" unless self.locked?
    raise ArgumentError, "deployment does not belong to stage" unless deployment.stage_id == self.id
    other_self = self.class.find(self.id, :lock => true)
    other_self.update_attribute(:locked_by_deployment_id, deployment.id)
    self.reload
  end
  
  protected
  def add_deployment_problem(key, desc)
    @deployment_problems = @deployment_problems || {}
    @deployment_problems[key] = desc
  end
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController

  before_filter :load_project
  before_filter :ensure_can_access_project
  before_filter :ensure_can_edit_project, :except => [:dashboard, :index, :show]
  
  # GET /projects/1/stages.xml
  def index
    @stages = current_project.stages
    respond_to do |format|
      format.xml  { render :xml => @stages.to_xml }
    end
  end

  # GET /projects/1/stages/1
  # GET /projects/1/stages/1.xml
  def show
    @stage = current_project.stages.find(params[:id])
    @task_list = [['All tasks: ', '']] + @stage.list_tasks.collect{|task| [task[:name], task[:name]]}.sort()
    @can_edit_project = current_user.can_edit?(@project)
    
    respond_to do |format|
      format.html # show.rhtml
      format.xml  { render :xml => @stage.to_xml }
    end
  end

  # GET /projects/1/stages/new
  def new
    @stage = current_project.stages.new
  end

  # GET /projects/1/stages/1;edit
  def edit
    @stage = current_project.stages.find(params[:id])
  end
  
  # GET /projects/1/stages/1/tasks
  # GET /projects/1/stages/1/tasks.xml
  def tasks
    @stage = current_project.stages.find(params[:id])
    @tasks = @stage.list_tasks
    
    respond_to do |format|
      format.html # tasks.rhtml
      format.xml  { render :xml => @tasks.to_xml }
    end
  end

  # POST /projects/1/stages
  # POST /projects/1/stages.xml
  def create
    @stage = current_project.stages.build(params[:stage])

    respond_to do |format|
      if @stage.save
        flash[:notice] = 'Stage was successfully created.'
        format.html { redirect_to project_stage_url(current_project, @stage) }
        format.xml  { head :created, :location => project_stage_url(current_project, @stage) }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @stage.errors.to_xml }
      end
    end
  end

  # PUT /projects/1/stages/1
  # PUT /projects/1/stages/1.xml
  def update
    @stage = current_project.stages.find(params[:id])
    
    respond_to do |format|
      if @stage.update_attributes(params[:stage])
        flash[:notice] = 'Stage was successfully updated.'
        format.html { redirect_to project_stage_url(current_project, @stage) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @stage.errors.to_xml }
      end
    end
  end

  # DELETE /projects/1/stages/1
  # DELETE /projects/1/stages/1.xml
  def destroy
    @stage = current_project.stages.find(params[:id])
    @stage.destroy

    respond_to do |format|
      flash[:notice] = 'Stage was successfully deleted.'
      format.html { redirect_to project_url(current_project) }
      format.xml  { head :ok }
    end
  end
  
  # GET /projects/1/stages/1/capfile
  # GET /projects/1/stages/1/capifile.xml
  def capfile
    @stage = current_project.stages.find(params[:id])

    respond_to do |format|
      format.html { render :layout => false, :content_type => 'text/plain' }
      format.xml  { render :xml => @stage.to_xml }
    end
  end
  
  # GET | PUT /projects/1/stages/1/recipes
  # GET /projects/1/stages/1/recipes.xml
  def recipes
    @stage = current_project.stages.find(params[:id])
    if request.put?
      @stage.recipe_ids = params[:stage][:recipe_ids] rescue []
      flash[:notice] = "Stage recipes successfully updated."
      redirect_to project_stage_url(current_project, @stage)
    else
      respond_to do |format|
        format.html { render }
        format.xml  { render :xml => @stage.recipes.to_xml }
      end
    end
  end
  
end

app/helpers/stages_helper.rb
module StagesHelper
  
  def display_deployment_problems(stage)
    out =  "<ul>"
    stage.deployment_problems.each do |k,v|
      out += "<li>#{v}</li>"
    end
    out += "</ul>"
    return out
  end
  
  # returns the escaped format of a config value
  def capfile_cast(val)
    casted_val = Webistrano::Deployer.type_cast(val).class

    if casted_val == String || casted_val == ActiveSupport::SafeBuffer
      val.inspect
    elsif casted_val == Symbol
      val.to_s
    elsif casted_val == Array
      val.to_s
    elsif casted_val == Hash
      val.to_s
    elsif (casted_val == TrueClass ) || (casted_val == FalseClass)
      val
    elsif casted_val == NilClass
      'nil'
    end

  end

  
end

app/views/stages/_configs.html.erb
<% if @stage.configuration_parameters.empty? %>
  <br/>
    No stage specific configuration added yet. Stage specific configuration entries override project configuration entries. 
    Typical examples are a different repository path (e.g. trunk) or a different Rails environment.
    Please add configuration entries.
  <br/>
<% else %>
  <table class="sortable">
    <tr>
      <th width="1%">Name</th>
      <th width="98%">Value</th>
      <th width="1%">Prompt?</th>
    </tr>
  <% for config in @stage.configuration_parameters %>
    <tr class="<%= cycle :even, :odd, :name => 'configs' %>">
      <td title="<%= config.name %>"><%= truncate(h(config.name), :length => 25) %></td>
      <td title="<%= config.value %>"><%= truncate(hide_password_in_value(config), :length => 45) %></td>
      <td><%= config.prompt_status_in_html %></td>
      <td><%= link_to 'Edit', edit_project_stage_stage_configuration_path(@project, @stage, config) %></td>
      <td><%= link_to 'Delete', project_stage_stage_configuration_path(@project, @stage, config), :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
  </table>
<% end %>

app/views/stages/_deployments.html.erb
<% if @stage.deployments.empty? %>
  <br/>
    This stage was never deployed. 
  <br/>
<% else %>
  <% @stage.recent_deployments.each do |deployment| %>
    <%= render(:partial => 'deployments/list_item', :locals => {:deployment => deployment}) %>
  <% end %>
<% end %>
<br />
<% if @stage.deployment_possible? %>
  <%= link_to 'New deployment', new_project_stage_deployment_path(current_project, @stage), :class => 'arrow_link' %> <%= (@stage.deployments.count > 1) ? '|' : '' %>
<% else %>
  A deployment is currently not possible:<br />
  <%= display_deployment_problems(@stage) %>
<% end %>
<% if @stage.deployments.count > 1 %>
  <%= link_to "Complete deployment history", project_stage_deployments_path(current_project, @stage), :class => 'arrow_link' %>
<% end %>

app/views/stages/_effective_config.html.erb
<h3>Effective Configuration</h3>

<% if @stage.effective_configuration.empty? %>
  <br/>
    No effective configuration present. The effective configuration is the result of the stage 
    specific configuration entries overriding the project configuration entries. 
  <br/>
<% else %>
  <table class="sortable">
    <tr>
      <th width="1%">Name</th>
      <th width="98%">Value</th>
      <th width="1%">Prompt</th>
    </tr>
  <% @stage.effective_configuration.each do |conf| %>
    <tr class="<%= cycle :even, :odd, :name => 'effective_conf' %>">
      <td title="<%= conf.name %>"><%= truncate(h(conf.name), :length => 25) %></td>
      <td title="<%= conf.value %>"><%= truncate(hide_password_in_value(conf), :length => 45) %></td>
      <td><%= conf.prompt_status_in_html %></td>
    </tr>
  <% end %>
  </table>
<% end %>

app/views/stages/_form.html.erb
<p>
  <b>Name</b> (e.g. 'Prod', 'Test', 'Dev')<br />
  <%= text_field 'stage', :name %>
</p>

<p>
  <b>Alert these emails on deploy</b> (separated by space)<br />
  <%= text_field 'stage', :alert_emails, :style =>'width:330px' %>
</p>

app/views/stages/_recipes.html.erb
<% if @stage.recipes.empty? %>
  <br/>
    No recipes configured yet.<br />
    <%= link_to 'Recipes', recipes_path %> are custom Capistrano tasks and variables that can be used across stages.
  <br/>
<% else %>
  <table class="sortable">
    <tr>
      <th width="40%">Name</th>
      <th width="60%">Description</th>
    </tr>
    <% for recipe in @stage.recipes.ordered %>
      <tr class="<%= cycle :even, :odd, :name => 'recipes'  %>">
        <td><%= link_to recipe.name, recipe_path(recipe) %></td>
        <td><%= recipe.description %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/stages/_roles.html.erb
<% if @stage.hosts.empty? %>
  <p>
    No hosts for this stage. A host is a physical host that this stage should deploy to.
    Please add a host.
  </p>
<% else %>
  <table class="sortable">
    <tr>
      <th width="25%">Host</th>
      <th width="25%">Role</th>
      <th width="24%">SSH Port</th>
      <th width="25%">Attributes</th>
      <th width="1%">Status</th>
    </tr>
  <% for role in @stage.roles %>
    <tr class="<%= cycle :even, :odd, :name => 'roles' %>">
      <td><%= link_to role.host.name, host_path(role.host) %></td>
      <td><%= role.name %></td>
      <td><%= role.ssh_port || 'default' %></td>
      <td><%= role.role_attribute_hash.inspect unless role.role_attribute_hash.blank?  %></td>
      <td><%= simple_format role.status_in_html %></td>
      <td><%= link_to 'Edit', edit_project_stage_role_path(@project, @stage, role) %></td>
      <td><%= link_to 'Delete', project_stage_role_path(@project, @stage, role), :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
  </table>
<% end %>

app/views/stages/capfile.html.erb
load 'deploy'

# ================================================================
# ROLES
# ================================================================

<% @stage.roles.each do |role| %>
	<% if role.role_attribute_hash.blank? -%>
		role :<%= raw role.name %>, <%= raw capfile_cast(role.hostname_and_port).to_s %>
	<% else -%>
		role :<%= raw role.name %>, <%= raw capfile_cast(role.hostname_and_port) %>, <%= raw role.role_attribute_hash.inspect %>
	<% end -%>
<% end %>

# ================================================================
# VARIABLES
# ================================================================

# Webistrano defaults
set :webistrano_project, <%= raw capfile_cast(@stage.project.webistrano_project_name) %>
set :webistrano_stage, <%= raw capfile_cast(@stage.webistrano_stage_name) %>

<% @stage.non_prompt_configurations.each do |effective_conf| %>
	set :<%= raw effective_conf.name.to_sym %>, <%= raw capfile_cast(effective_conf.value) %>
<% end %>

<% @stage.prompt_configurations.each do |conf| %>
	set(:<%= raw conf.name %>) do
	Capistrano::CLI.ui.ask "Please enter '<%= raw conf.name.to_sym %>': "
	end
<% end %>

# ================================================================
# TEMPLATE TASKS
# ================================================================

<%= raw @stage.project.tasks %>

# ================================================================
# CUSTOM RECIPES
# ================================================================

<% @stage.recipes.each do |recipe| %>
	<%= raw recipe.body %>
<% end %>

app/views/stages/edit.html.erb
<% flashed_errors(:stage) %>

<%= form_for(:stage, :url => project_stage_path(@project, @stage), :html => { :method => :put }) do |f| %>
  
  <%= render(:partial => 'form' ) %>
  
  <%= link_to 'Back to stage', project_stage_path(@project, @stage), :class => 'arrow_link ontheright', :style => 'margin-right: 330px' %>

  <p>
    <%= submit_tag "Update" %>
  </p>
<% end %>

<% content_for(:breadcrumb) do %>
    <%= link_to "Back to stage", project_stage_path(current_project, current_stage), :style => "float:right", :class => "arrow_link" %>
    <%= link_to "Projects", projects_path %> &gt; 
    Project <%= link_to current_project.name, project_path(current_project) %> &gt; 
    Stage <%= link_to current_stage.name, project_stage_path(current_project, current_stage) %>  &gt; 
    Edit
<% end %>

<% content_for(:page_title) do %>
  <% @page_title = "Edit project #{h(current_project.name)}" %>
  <h2>Edit</h2>
<% end %>

app/views/stages/new.html.erb
<% flashed_errors(:stage) %>

<%= form_for(:stage, :url => project_stages_path(current_project)) do |f| %>
  
  <%= render(:partial => 'form' ) %>
  
  <%= link_to 'Back to project', project_path(current_project), :class => 'arrow_link ontheright', :style => 'margin-right: 330px' %>

  <p>
    <%= submit_tag "Create" %>
  </p>
<% end %>

<% content_for(:breadcrumb) do %>
    <%= link_to "Back to project", project_path(current_project), :style => "float:right", :class => "arrow_link" %>
    <%= link_to "Projects", projects_path %> &gt; 
    Project <%= link_to current_project.name, project_path(current_project) %> &gt;  
    New
<% end %>

<% content_for(:page_title) do %>
  <% @page_title = "New stage for project #{h(current_project.name)}" %>
  <h2>New stage</h2>
<% end %>

app/views/stages/recipes.html.erb
<%= form_for(:stage, :url => recipes_project_stage_path(@project, @stage), :html => { :method => :put }) do |f| %>

  <fieldset class="fieldset">
    <legend>Recipes to use</legend>
    
    <% if Recipe.count > 0 %>
    
      <table class="sortable">
        <tr>
          <th width="1%">Use</th>
          <th width="39%">Name</th>
          <th width="60%">Description</th>
        </tr>
        <% for recipe in Recipe.find(:all, :order => 'name ASC') %>
          <tr class="<%= cycle :even, :odd, :name => 'recipes'  %>">
            <td><input type="checkbox" value="<%= recipe.id %>" name="stage[recipe_ids][]" id="stage_recipe_ids_<%= recipe.id %>" <%= @stage.recipes.include?(recipe) ? 'checked="checked"' : '' %>/></td>
            <td><%= link_to recipe.name, recipe_path(recipe) %></td>
            <td><%= recipe.description %></td>
          </tr>
        <% end %>
      </table>
      
      <br />
      <p>
        <%= submit_tag "Update used recipes" %>
      </p>
      
    <% else %>
     No recipes present<br /><br />
    <% end %>
  
  </fieldset>    
    
    
  
  
<% end %>
<br />
<%= link_to 'Back to stage', project_stage_path(current_project, current_stage), :class => 'arrow_link'  %>

<% content_for(:breadcrumb) do %>
    <%= link_to "Back to stage", project_stage_path(current_project, current_stage), :style => "float:right", :class => "arrow_link" %>
    <%= link_to "Projects", projects_path %> &gt; 
    Project <%= link_to current_project.name, project_path(current_project) %> &gt; 
    Stage <%= link_to current_stage.name, project_stage_path(current_project, current_stage) %>  &gt; 
    Recipes management
<% end %>

<% content_for(:page_title) do %>
  <% @page_title = "Recipes management for stage: #{h @stage.name}"%>
  <h2>Recipes management</h2>
<% end %>

app/views/stages/show.html.erb
<div class="special_box">
  <div class="special_box_top"></div>
  <div class="special_box_middle deployments_box">
   <p><%= link_to 'Deploy', new_project_stage_deployment_path(current_project, @stage) + '?task=deploy', :class => 'arrow_link' %></p>
   <p><%= link_to 'Deploy and migrate', new_project_stage_deployment_path(current_project, @stage) + '?task=deploy:migrations', :class => 'arrow_link' %></p>
   <p><%= link_to 'Restart app servers', new_project_stage_deployment_path(current_project, @stage) + '?task=deploy:restart', :class => 'arrow_link' %></p>
   <p><%= link_to 'Setup', new_project_stage_deployment_path(current_project, @stage) + '?task=deploy:setup', :class => 'arrow_link' %></p>
   <p>
     <%= select_tag('task', options_for_select(@task_list)) %>
   </p>
   <p>
     <%= link_to 'Execute', new_project_stage_deployment_path(current_project, @stage), :class => 'arrow_link', 
         :onclick => "location.href='#{new_project_stage_deployment_path(current_project, @stage)}?task=' + $F('task'); return false" %> |
     <%= link_to 'Info', tasks_project_stage_path(current_project, @stage), :class => 'arrow_link',
         :onclick => "location.href='#{tasks_project_stage_path(current_project, @stage)}#' + $F('task'); return false" %>
   </p>
    </div>
  <div class="special_box_bottom"></div>
</div>

<div class="box">
  <div class="box_top"></div>
  <div class="box_middle">
	  <p>
	    <b>Name:</b>
		   <%= @stage.name %>
		</p>
		<p>
		  <b>Project:</b>
		  <%= link_to @stage.project.name, project_url(current_project) %>
		</p>
		<p>
		  <b>Alert on deploy:</b>
		  <%= @stage.alert_emails %>
		</p>
		<p>
		  <b>#Hosts:</b>
		  <%= @stage.hosts.count %>
		</p>
		<br />
    <%- if @can_edit_project -%>
		  <%= link_to 'Edit stage', edit_project_stage_path(current_project, @stage), :class => 'arrow_link' %> | 
		  <%= link_to 'Delete stage', project_stage_path(current_project, @stage), :confirm => 'Are you sure?', :method => :delete, :class => 'arrow_link'  %> | 
		<%- end -%>
		<%= link_to 'Export capfile', {:action => 'capfile', :project_id => current_project, :id => @stage}, {:onclick => "loadWindow('#{url_for(:action => 'capfile', :project_id => current_project, :id => @stage)}'); return false", :class => 'arrow_link'} %>
	</div>	
  <div class="box_bottom"></div>
</div>


<div class="clear"></div>
<br>

<fieldset class="fieldset">
  <legend>Stage specific configuration</legend>
  <%= render(:partial => 'configs')%>
  <br />
  <div id="effective_config" style="display:none;">
    <%= render(:partial => 'effective_config')%>
    <br />
  </div>
  <%- if @can_edit_project -%>
    <%= link_to 'New configuration', new_project_stage_stage_configuration_path(current_project, @stage), :class => 'arrow_link' %> | 
  <%- end -%>
  <a id="s_e_c" href="#" onclick="show_effective_config(); return false" class="arrow_link">Show effective configuration</a>
  <a id="h_e_c" href="#" onclick="hide_effective_config(); return false" class="arrow_link" style="display:none;">Hide effective configuration</a>
</fieldset>

<br /><br />

<fieldset class="fieldset">
  <legend>Used recipes</legend>
  <%= render(:partial => 'recipes')%>
  <br />
  <%- if @can_edit_project -%>
    <%= link_to 'Manage stage recipes', {:action => 'recipes', :project_id => current_project, :id => @stage} , :class => 'arrow_link'%>
  <%- end -%>
</fieldset>

<br /><br />

<fieldset class="fieldset">
  <legend>Deployed hosts</legend>
  <%= render(:partial => 'roles')%>
  <br />
  <%= link_to 'Add host', new_project_stage_role_path(current_project, @stage) , :class => 'arrow_link'%>
</fieldset>

<br /><br />

<fieldset class="fieldset">
  <legend>Recent deployment history</legend>
  <%= render(:partial => 'deployments')%>
</fieldset>

<br />
<% content_for(:page_scripts) do %>
 <script type="text/javascript">
 
   function show_effective_config(){
     $('h_e_c').show();
     $('s_e_c').hide();
     $('effective_config').show();
   }
   
   function hide_effective_config(){
      $('h_e_c').hide();
      $('s_e_c').show();
      $('effective_config').hide();
    }
 </script>
<% end %>

<% content_for(:breadcrumb) do %>
    <%= link_to "Back to project", project_path(@project), :style => "float:right", :class => "arrow_link" %>
    <%= link_to "Projects", projects_path %> &gt; 
    Project <%= link_to current_project.name, project_path(current_project) %> &gt; 
    Stage <%= link_to current_stage.name, project_stage_path(current_project, current_stage) %>
<% end %>

<% content_for(:page_title) do %>
  <% @page_title = "Project #{h(current_project.name)} - Stage #{h(@stage.name)}"%>
  <h2>Stage <%= link_to @stage.name, project_stage_path(current_project, @stage) %></h2>
<% end %>

app/views/stages/tasks.html.erb
<fieldset class="fieldset">
  <legend>All Tasks</legend>
    <table>
    <% @tasks.sort{|a, b| a[:name] <=> b[:name]}.each do |task| %>
	<tr>
   	<td valign="top"><%= link_to task[:name], new_project_stage_deployment_path(current_project, @stage) + "?task=#{task[:name]}", :class => 'arrow_link', :name => task[:name]%></td>
   	<td>&nbsp;&nbsp;</td>
	  <td valign="top"><%= simple_format task[:description] %></td>
	</tr>
    <% end %>
    </table>

</fieldset>

<br />
<%= link_to 'Back to stage', project_stage_path(@project, @stage), :class => 'arrow_link'  %>

<% content_for(:breadcrumb) do %>
    <%= link_to "Back to stage", project_stage_path(current_project, current_stage), :style => "float:right", :class => "arrow_link" %>
    <%= link_to "Projects", projects_path %> &gt; 
    Project <%= link_to current_project.name, project_path(current_project) %> &gt; 
    Stage <%= link_to current_stage.name, project_stage_path(current_project, current_stage) %> &gt; 
    Task list
<% end %>

<% content_for(:page_title) do %>
  <% @page_title = "Task list for stage: #{h @stage.name}"%>
  <h2>Task list</h2>
<% end %>