config/routes.rb
Www::Application.routes.draw do
  
  resources :auth_sources
  resources :auth_sources_ldap

  match '/' => 'projects#dashboard', :as => :home
  match ':controller/service.wsdl' => '#wsdl'

  resources :hosts
  resources :recipes do
    collection do
      get :preview
    end
  end

  resources :projects do
    member do
      get :dashboard
    end

    resources :project_configurations
    resources :stages do
      match :recipes, :on => :member
      member do
        get :capfile
        get :tasks
      end

      resources :stage_configurations
      resources :roles
      resources :deployments do
        collection do
          get :latest
        end

        member do
          post :cancel
        end
      end
    end
  end

  resources :users do

    member do
      get :deployments
      post :enable
    end
  end

  resources :sessions do
    collection do
      get :version
    end
  end
  


  match '/signup' => 'users#new', :as => :signup
  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/stylesheets/application.css' => 'stylesheets#application', :as => :stylesheet
  match '/:controller(/:action(/:id))'
end

app/views/layouts/_favorites.html.erb
<div id="projects_open_content" style="<%=h show_if_opened(status) %>">
<% projects = Project.find(:all, :conditions => { :favorite => 1 },  :order => "name ASC") %>
  <% if projects.count > 0 %>
        <%= render(:partial => 'layouts/project_view', :locals => { :projects => projects } )%>
  <% else %>
    <div class="menu_item">No project created yet</div>
   <a href="<%= new_project_path %>" class="menu_link  menu_link_create">New project</a>
  <% end %>
</div>
<div id="projects_closed_content" style="<%=h show_if_closed(status) %>">
  <a href="javascript:open_menu_box('projects')" class="menu_link  menu_link_create">
	  <div class="menu_link_title">
	    <%=h pluralize(projects.count, 'project')%>
	  </div>
  </a>
</div>

app/views/layouts/_flash.html.erb
<div class="flash_box">
  <div class="flash_box_top"></div>
  <div id="flash" class="flash_box_middle">
    <div class="flash_text_info"><%= text %></div>
  </div>
  <div class="flash_box_bottom"></div>
</div>

app/views/layouts/_flash_error.html.erb
<div class="flash_box">
  <div class="flash_box_top"></div>
  <div id="flash" class="flash_box_middle">
    <div class="flash_text_error"><%= text %></div>
  </div>
  <div class="flash_box_bottom"></div>
</div>

app/views/layouts/_flash_locking.html.erb
<div class="flash_box">
  <div class="flash_box_top"></div>
  <div id="flash" class="flash_box_middle">
    <div class="flash_text_locking"><%= text %></div>
  </div>
  <div class="flash_box_bottom"></div>
</div>

app/views/layouts/_hosts.html.erb
<div id="hosts_open_content" style="<%= show_if_opened(status) %>">
  <% if @sidebar_hosts.present? %>
    <% for host in @sidebar_hosts %>
      <a href="<%= host_path(host) %>" class="menu_link <%= active_link_class(host) %>" title="<%= host.name %>">
  	    <div class="menu_link_title">
  	      <%= host.name %>
  	    </div>
      </a>
    <% end %>
  <% else %>
    <div class="menu_item">No host created yet</div>
    <%- if current_user.can_manage_hosts? -%>
      <a href="<%= new_host_path %>" class="menu_link  menu_link_create">
  	    <div class="menu_link_title">
  	      New host
  	    </div>
  	  </a>
  	<%- end -%>
  <% end %>
</div>
<div id="hosts_closed_content" style="<%= show_if_closed(status) %>">
  <a href="javascript:open_menu_box('hosts')" class="menu_link  menu_link_create">
	  <div class="menu_link_title">
	    <%=h pluralize(@sidebar_hosts.length, 'host')%>
	  </div>
  </a>
</div>  

app/views/layouts/_menu.html.erb
<%= render(:partial => 'layouts/menu_box', :locals => {
                                             :box_type => 'projects', 
                                             :status => controller_in_use_or(ProjectsController, :open, @sidebar_projects), 
                                             :path => projects_path } )%>

<%= render(:partial => 'layouts/menu_box', :locals => {
                                             :box_type => 'hosts', 
                                             :status => controller_in_use_or(HostsController, :closed, @sidebar_hosts), 
                                             :path => hosts_path } )%>

<%= render(:partial => 'layouts/menu_box', :locals => {
                                             :box_type => 'recipes', 
                                             :status => controller_in_use_or(RecipesController, :closed, @sidebar_recipes), 
                                             :path => recipes_path } )%>

<%= render(:partial => 'layouts/menu_box', :locals => {
                                             :box_type => 'users', 
                                             :status => controller_in_use_or(UsersController, :closed, @sidebar_users), 
                                             :path => users_path } )%>

app/views/layouts/_menu_box.html.erb
<div class="menu_box">
  <div class="menu_box_header">
	  <div class="menu_box_arrow"><%= image_tag('peritor_theme/menu_arrow_down.gif', :onclick => "close_menu_box('#{h(box_type)}'); return false", :id => "#{h(box_type)}_arrow_down", :style => "#{h(show_if_opened(status))};") %><%= image_tag('peritor_theme/menu_arrow_right.gif', :onclick => "open_menu_box('#{h(box_type)}'); return false", :id => "#{h(box_type)}_arrow_right", :style => "#{h(show_if_closed(status))};") %></div>
<div class="menu_title"><%= link_to box_type.capitalize, path %></div>
  </div>
  <div class="menu_box_body">
    <%= render(:partial => "layouts/#{box_type}", :locals => {:status => status} )%>
    <div class="clear"></div>
  </div>
  <div class="menu_box_footer"></div>
</div>

app/views/layouts/_project_view.html.erb
<% for project in projects %>
      <a href="<%= project_path(project) %>" class="menu_link <%=h active_link_class(project) %>" title="<%=h project.name %>">
                    <div class="menu_icons">

                  <%= image_tag('peritor_theme/arrow_menu_right.gif', :width => '20', :height => '20', :border => '0', :style => "#{h( do_not_show_stages_of_project(project))}", :id => "#{h(dom_id(project))}_arrow_right", :onclick => "open_menu('#{h( dom_id(project))}'); return false;" )%>

                  <%= image_tag('peritor_theme/arrow_menu_down.gif', :width => '20', :height => '20', :border => '0', :style => "#{h( show_stages_of_project(project))}", :id => "#{h(dom_id(project))}_arrow_down", :onclick => "close_menu('#{h( dom_id(project))}'); return false;" )%></div>
                    <div class="menu_link_title has_submenu">
                      <%=h project.name %>
                    </div>
      </a>
      <div id="<%=h dom_id(project) %>_stages" style="<%=h show_stages_of_project(project) %>">
            <% if project.stages.count > 0 %>
        <% for stage in project.stages %>
          <a href="<%= project_stage_path(project, stage) %>" class="menu_link <%=h active_link_class(stage) %>" title="<%=h stage.name %>">
                  <div class="menu_link_title" style="padding-left: 30px; *padding-left: 33px"><%=h stage.name %></div>
                            </a>
        <% end %>
                <% else %>
      <a href="<%= new_project_stage_path(project) %>" class="menu_link menu_link_new">
              <div class="menu_link_title" style="padding-left: 30px; *padding-left: 33px">New stage</div>
            </a>
                <% end %>
      </div>
<% end %>

app/views/layouts/_projects.html.erb
<div id="projects_open_content" style="<%= show_if_opened(status) %>">
  <% if @sidebar_projects.present? %>
    <% for project in @sidebar_projects %>
      <a href="<%= project_path(project) %>" class="menu_link <%= active_link_class(project) %>" title="<%= project.name %>">
		    <div class="menu_icons">
		  
		  <%= image_tag('peritor_theme/arrow_menu_right.gif', :width => '20', :height => '20', :border => '0', :style => "#{h( do_not_show_stages_of_project(project))}", :id => "#{h(dom_id(project))}_arrow_right", :onclick => "open_menu('#{h( dom_id(project))}'); return false;" )%>
		  
		  <%= image_tag('peritor_theme/arrow_menu_down.gif', :width => '20', :height => '20', :border => '0', :style => "#{h( show_stages_of_project(project))}", :id => "#{h(dom_id(project))}_arrow_down", :onclick => "close_menu('#{h( dom_id(project))}'); return false;" )%></div>
		    <div class="menu_link_title has_submenu">
		      <%= project.name %>
		    </div>
      </a>
      <div id="<%= dom_id(project) %>_stages" style="<%= show_stages_of_project(project) %>">
	    <% if project.stages.present? %>
        <% for stage in project.stages %>
          <a href="<%= project_stage_path(project, stage) %>" class="menu_link <%= active_link_class(stage) %>" title="<%= stage.name %>">
	          <div class="menu_link_title" style="padding-left: 30px; *padding-left: 33px"><%= stage.name %></div>
			    </a>
        <% end %>
		<% elsif current_user.can_edit?(project) %>
      <a href="<%= new_project_stage_path(project) %>" class="menu_link menu_link_new">
	      <div class="menu_link_title" style="padding-left: 30px; *padding-left: 33px">New stage</div>
	    </a>
		<% end %>
      </div>
    <% end %>
  <% else %>
    <div class="menu_item">No project created yet</div>
   <a href="<%= new_project_path %>" class="menu_link  menu_link_create">New project</a>
  <% end %>
</div>
<div id="projects_closed_content" style="<%= show_if_closed(status) %>">
  <a href="javascript:open_menu_box('projects')" class="menu_link  menu_link_create">
	  <div class="menu_link_title">
	    <%=h pluralize(@sidebar_projects.length, 'project')%>
	  </div>
  </a>
</div>

app/views/layouts/_recipes.html.erb
<div id="recipes_open_content" style="<%= show_if_opened(status) %>">
  <% if @sidebar_recipes.present? %>
    <% for recipe in @sidebar_recipes %>
      <a href="<%= recipe_path(recipe) %>" class="menu_link <%= active_link_class(recipe) %>" title="<%= recipe.name %>">
		    <div class="menu_link_title">
		      <%= recipe.name %>
		    </div>
	    </a>
    <% end %>
  <% else %>
    <div class="menu_item">No recipe created yet</div>
      <%- if current_user.can_manage_recipes? -%>
        <a href="<%= new_recipe_path %>" class="menu_link  menu_link_create">
      	  <div class="menu_link_title">
      	    New recipe
      	  </div>
    	  </a>
    	<%- end -%>
  <% end %>
</div>
<div id="recipes_closed_content" style="<%= show_if_closed(status) %>">
  <a href="javascript:open_menu_box('recipes')" class="menu_link  menu_link_create">
	  <div class="menu_link_title">
	    <%=h pluralize(@sidebar_recipes.length, 'recipe')%>
	  </div>
  </a>
</div>

app/views/layouts/_users.html.erb
<div id="users_open_content" style="<%= show_if_opened(status) %>">
  <% if @sidebar_users.present? %>
    <% for user in @sidebar_users %>
      <a href="<%= user_path(user) %>" class="menu_link <%= active_link_class(user) %>" title="<%= user.login %>">
		    <div class="menu_link_title">
		      <%= user.login %>
		    </div>
	    </a>
    <% end %>
  <% else %>
    <div class="menu_item">No user created yet</div>
    <a href="<%= new_user_path %>" class="menu_link  menu_link_create">
	    <div class="menu_link_title">
	      New user
	    </div>
	  </a>
  <% end %>
</div>
<div id="users_closed_content" style="<%= show_if_closed(status) %>">
  <a href="javascript:open_menu_box('users')" class="menu_link  menu_link_create">
	  <div class="menu_link_title">
	    <%=h pluralize(@sidebar_users.length, 'user')%>
	  </div>
  </a>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <meta name="description" content="Peritor Webistrano - Capristrano Deployment the easy way" />
  <meta name="keywords" content="rubyonrails ruby rails capistrano deployment" />
  <title>Peritor Webistrano - <%= @page_title %></title>
  <link rel="shortcut icon" href="/favicon.ico" />
  <%= javascript_include_tag :defaults %>
  <%= stylesheet_link_tag 'application' %>
  <%= yield :page_scripts %>
</head>

<body>
  <div id="app_top">
    <div id="header">
      <div id="header_claim">Capistrano deployment the easy way</div>
      <a href="<%= home_path %>"><%= image_tag('peritor_theme/webistrano_logo.gif', :border => '0')%></a>
    </div>
    <div id="main_content">
      <% if logged_in? %>
        <div class="menu">
          <%= render(:partial => 'layouts/menu') %>
        </div>
      <% else %>
        <div style="width:80px; float:left;">&nbsp;</div>
      <% end %>
      <div class="content">
		<div class='breadcrumb'>
        	<%= yield :breadcrumb %>
		</div>
        <%= yield :flash_content %>
        <%= yield :page_title %>

        <% unless flash[:notice].blank? %>
          <%= nice_flash(flash[:notice]) %>
        <% end %>

        <% unless flash[:error].blank? %>
          <%= error_flash(flash[:error]) %>
        <% end %>

        <%= yield :action_box %>

        <%= yield  %>
      </div>
      <div class="clear"></div>
    </div>
  </div>
  <div id="app_bottom"></div>

  <div id="footer">
    <div id="footer_logged">
      <% if logged_in? %>
       Logged in as <%= link_to current_user.login, user_path(current_user) %> | <%= link_to 'Logout', logout_path %>
      <% end %>
    </div>
    Copyright &copy; 2007, 2008, 2009 | Version <%= WEBISTRANO_VERSION %> | <a href="http://labs.peritor.com/webistrano" target="_blank">http://labs.peritor.com/webistrano</a>
  </div>
</body>

</html>